# Generated by Django 5.0.6 on 2024-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('homeworld', models.CharField(blank=True, max_length=100, null=True)),
                ('wiki', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('born', models.IntegerField(blank=True, null=True)),
                ('bornLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('died', models.IntegerField(blank=True, null=True)),
                ('diedLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('hairColor', models.CharField(blank=True, max_length=50, null=True)),
                ('eyeColor', models.CharField(blank=True, max_length=50, null=True)),
                ('skinColor', models.CharField(blank=True, max_length=50, null=True)),
                ('cybernetics', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliations', models.JSONField(blank=True, null=True)),
                ('masters', models.JSONField(blank=True, null=True)),
                ('apprentices', models.JSONField(blank=True, null=True)),
                ('formerAffiliations', models.JSONField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('class_field', models.CharField(blank=True, max_length=100, null=True)),
                ('sensorColor', models.CharField(blank=True, max_length=50, null=True)),
                ('platingColor', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment', models.JSONField(blank=True, null=True)),
                ('era', models.JSONField(blank=True, null=True)),
                ('kajidic', models.CharField(blank=True, max_length=100, null=True)),
                ('armament', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(blank=True, to='api.character')),
            ],
        ),
    ]
