# Generated by Django 5.0.6 on 2024-06-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='born',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
